name: "Analyze Workflow"
description: "Analyze and give feedback on the type of git workflow used"
inputs:
  working-directory:
    description: "go-gopher working directory, default is project root"
    required: false
runs:
  using: "docker"
  image: "docker://gitgopher:our-image"
branding:
  icon: "alert-triangle"
  color: "blue"
